### ISSUE TITLE
About 3d-pose-baseline-vmd IndexError

### ISSUE THREAD

**Issue by ShuttleDDD** [peterljq/OpenMMD#10]
while following the instruction and trying to run OpenposeTo3D.bat, after inserting the number of people, the program keeps throwing out IndexError, such as 
File "src/openpose_3dpose_sandbox_vmd.py", line 74, in read_openpose_json
    _tmp_data = data["people"][idx]["pose_keypoints_2d"]
IndexError: list index out of range
or
 File "src/openpose_3dpose_sandbox_vmd.py", line 110, in read_openpose_json
    _tmp_points[n][_data_idx] = _tmp_data[o]
IndexError: list index out of range

Any ideas? I'm really confused
I've try different tensorflow and cuda versions, the problem remains.

**Comment by peterljq** [comment]
请再复查下第一步的OpenPose是否能正常运行，是否下载并调用了Google Drive链接里的全套Pretrained Parameter呢？

**Comment by ShuttleDDD** [comment]
经过检查发现是因为我用了openpose1.4.0的版本，用1.3.0不会有这个问题……

**Comment by peterljq** [comment]
好的，了解👌

**Comment by Montage-LSM** [comment]
> 经过检查发现是因为我用了openpose1.4.0的版本，用1.3.0不会有这个问题......

HI哥们我遇到一个类似的问题，能不能加 Q请教一下：564303494   微信：lsm2424634754
