### ISSUE TITLE
About convert to vmd file

### ISSUE THREAD

**Issue by xiaohong23** [peterljq/OpenMMD#11]
Thank you very much for sharing your wonderful project.  I am doing fine until the last step.  It gives me this error message: "usage: pos2vmd_multi.py [-h] [-t TARGET] [-b BONE] [-v VERBOSE] [-u UPRIGHT]                        [-c CENTERXY] [-z CENTERZ] [-x XANGLE]                        [-d DDECIMATION] [-m MDECIMATION] [-i IDECIMATION]                        [-a ALIGNMENT] [-k LEGIK] [-e HEELPOS]pos2vmd_multi.py: error: unrecognized arguments: -s 1". If I remove the s parameter in the last line of the bat file, it will execute and give me a vmd file but the result is not good.  I was wondering if you could point out what possibly going wrong with my passing the s factor.  Thanks!

**Comment by peterljq** [comment]
最后一步的bat里一般是默认赋值的，我对mmd的配置研究不多，不过产生vmd的这一步确实是可以自行做不少调整的。

**Comment by masonzaizhe2** [comment]
Are you guys still maintaining the scripts? This error still exists.

**Comment by peterljq** [comment]
> Are you guys still maintaining the scripts? This error still exists.

In the 3DToVmd.bat file, you can try deleting the '-s %SMOOTH_TIMES%' at the last line of script. The error should be solved.

**Comment by Jacob12138xieyuan** [comment]
> Thank you very much for sharing your wonderful project. I am doing fine until the last step. It gives me this error message: "usage: pos2vmd_multi.py [-h] [-t TARGET] [-b BONE] [-v VERBOSE] [-u UPRIGHT] [-c CENTERXY] [-z CENTERZ] [-x XANGLE] [-d DDECIMATION] [-m MDECIMATION] [-i IDECIMATION] [-a ALIGNMENT] [-k LEGIK] [-e HEELPOS]pos2vmd_multi.py: error: unrecognized arguments: -s 1". If I remove the s parameter in the last line of the bat file, it will execute and give me a vmd file but the result is not good. I was wondering if you could point out what possibly going wrong with my passing the s factor. Thanks!

rename the csv file to english or number, then you are good to go
