### ISSUE TITLE
Hi, do I need to change the default csv file?

### ISSUE THREAD

**Issue by OptimusPrimeCao** [peterljq/OpenMMD#12]
I have a miku model, but after I import the generated vmd and fbx to the MMD software, I found  
the miku move strangely(not the same movement in the input video). Do I need to change some parameter or change the bone csv file? Thanks!

**Comment by peterljq** [comment]
I am glad to see that the vmd file has been successfully generated. Under your situation, you can either edit the bone csv file to adjust the model or you may directly modify the vmd actions in MikuMikuDance. 你可以选择修改骨架配置，或者直接在MikuMikuDance里面修改动作。

**Comment by OptimusPrimeCao** [comment]
你好，我能生成vmd,但是倒入到mmd里动作始终不动。我怀疑是不是关键点对应的问题。请问你的步骤中使用openpose输出的json的格式是什么？用openpose预测2d关键点这一步我没有使用你的代码，不知道是不是这里有问题

**Comment by OptimusPrimeCao** [comment]
你好，我能生成vmd,但是倒入到mmd里动作始终不对，卡通人物站立时也是偏着的。我怀疑是不是关键点对应的问题。请问你的步骤中使用openpose输出的json的格式是什么？是十八个点吗？顺序能说明一下吗？用openpose预测2d关键点这一步我没有使用你的代码，不知道我是不是这里有问题

**Comment by peterljq** [comment]
我觉得最好还是要用全套的代码，openpose预测2d的那一步会生成一系列json，你可以生成之后拆解看下顺序。

**Comment by OptimusPrimeCao** [comment]
我弄了两天了，始终结果不对。是个女孩跳舞的30s左右的小视频，生成的结果始终不对。请问您邮箱号是多少，能麻烦帮生成了看看效果吗，我邮箱发给您。非常感谢！

**Comment by peterljq** [comment]
具体的实现已经打包在readme里面的google drive链接，大概一个G左右，请尝试下用完整的包跑一次。我最近在忙阿里的实习入职，可能不太有时间帮您跑一次，非常抱歉🌚

**Comment by OptimusPrimeCao** [comment]
其实我就是阿里的，工作需要想使用你的工程做个demo.等你入职了我们可以钉钉交流。。。那我用你的全套代码生成好了，如果还有问题，能麻烦帮看看吗

**Comment by peterljq** [comment]
阿里前辈好😭，没问题没问题，很荣幸这个工程能帮到你们做demo，你先试下完整的包，里面parameter都已经train好了，有什么问题随时找我，邮箱peter.lo.sg@gmail.com

**Comment by OptimusPrimeCao** [comment]
好的，什么时候入职啊

**Comment by peterljq** [comment]
大概五月上中旬做到八月初，意向书已签。八月份还有华为的offer，所以还在和两边hr沟通时间，还有体检和校方手续要走，事情比较繁琐。OpenMMD是去年参选谷歌冬令营的项目，大概有五六个月了，当时啥也不懂，只会搬轮子调包，拼拼凑凑出来的😂。

**Comment by peterljq** [comment]
前辈视频有发邮箱嘛，我一会帮你跑下看看。

**Comment by OptimusPrimeCao** [comment]
太感谢了！发给你了哈，麻烦查收一下
