### ISSUE TITLE
convert to vmd

### ISSUE THREAD

**Issue by rookieplayerzhang** [peterljq/OpenMMD#13]
尝试 deleting the '-s %SMOOTH_TIMES%'编译显示 unknown encoding!求教如何解决

**Comment by peterljq** [comment]
你试下在配置文件里添加PYTHONIOENCODING，变量值为utf-8，看能否跑起来

**Comment by rookieplayerzhang** [comment]
非常感谢

**Comment by Jacob12138xieyuan** [comment]
rename the csv file to english or number
