### ISSUE TITLE
unrecognized arguments: -s 1

### ISSUE THREAD

**Issue by J-1n** [peterljq/OpenMMD#14]
Thanks for your great work! I've downloaded the fullpack and followed your instruction step by step. And I got (1) _openpose.avi, (2) _json(folder), and (3)_json_3d_20190515_152335_idx01(folder).
Then in the final step, when I run 3DToVmd.bat, it asked me to input the result folder path of the execution on 3d-pose-baseline-vmd.  Isn't the path of option (2) above? When I input the (2) path, then I just hit 'enter key' for default for the rest of the settings, and I got a error message: pos2vmd_multi.py: error: unrecognized arguments: -s 1

Am I importing a wrong path? 
And how to solve this problem?

**Comment by peterljq** [comment]
In the 3DToVmd.bat file, you can try deleting the '-s %SMOOTH_TIMES%' at the last line of script. The error should be solved.

**Comment by J-1n** [comment]
Thanks. I have the vmd file now, but here comes up with a new question in MMD. When I drag the vmd file to MMD with a model loaded, 

then it pops up a window and says 'This motion file is the data for 'Dummy Model Name 002'. You can regist the motion only same bone name. Are you OK?'

after clicking 'OK' button, the initial position of the model shifts to a high level. And when I hit play button, the model is like floating in the sky with weird motion.

So am I using a wrong bone file?
Should I prepare a bone file on my own for my model during the final 3DToVmd.bat step?

**Comment by peterljq** [comment]
If the VMD file has been successfully generated based on the default bone file, you may want to use Hatsune Miku models. If you want to use other models, you should generated the VMD file based on cooresponding bone file imported by yourself. Hope that helps :)

**Comment by J-1n** [comment]
Thanks for you patient answers! This time I got a .csv bone file by using PmxEditor based on another model, and when run 3DToVmd.bat again, it came up with a new 

error: File "applications\pos2vmd_multi.py", line 1727, in calc_center 
bone_upright_area = calc_triangle_area(neck_3d, right_leg_3d, left_leg_3d)
UnboundLocalError: local vairable 'neck_3d' referenced before assignment

Although I'm not an expert in coding, I checked out your code and I saw no problems of the codes, cuz the arg 'neck_3d' was given before the line 1727 in the 'for loop'.

So, it is really wired to get this error. I have no idea about it.
The attachment is the model and cooresponding bone file I've used.
Could you please have a look on that?
Thanks a lot!

[Miku bone and model.zip](https://github.com/peterljq/OpenMMD/files/3190274/Miku.bone.and.model.zip)
