### ISSUE TITLE
Json file structure for 2d json outputs per frame and input to 3d pose estimator ?

### ISSUE THREAD

**Issue by timtensor** [peterljq/OpenMMD#15]
Hello , 
What should be the format of the json files. In òrigirnal code the 2D json files from open pose to the 3d pose baselien is  `0000000000001_keypoint.json` what is the modified `sandbox` is expecting ?

**Comment by peterljq** [comment]
Hi, for this question you may ask [@mrzjy](https://github.com/mrzjy): jiayi.zhang9312@gmail.com . He has more knowledges on json relevance.
