### ISSUE TITLE
Simple tutorial on BiliBili site

### ISSUE THREAD

**Issue by mrzjy** [peterljq/OpenMMD#16]
Hi, thanks for the project! I appreciate it so much that I made a simple tutorial on BiliBili hoping I could help spread it ( If you don't mind~ ). I'm wondering if you might want to have a look or maybe point out some flaws in the blog ( https://www.bilibili.com/read/cv2835857 ), and maybe also respond to some comments, if any.

**Comment by SixiGit** [comment]
感谢帮忙制作教程来推广OpenMMD！最近在支付宝做算法实习，不太有时间继续开发，晚上回去会把你的教程加在README里，感谢👌
有问题可以加下我的大学邮箱或者QQ：
LUOJ0021@e.ntu.edu.sg
QQ：937314732


顺颂商祺！
| |
罗靳祺
邮箱：peter_0929@126.com
|

签名由 网易邮箱大师 定制

On 06/09/2019 17:59, Jiayi wrote:

Hi, thanks for the project! I appreciate it so much that I made a simple tutorial on BiliBili hoping I could help spread it ( If you don't mind~ ). I'm wondering if you might want to have a look or maybe point out some flaws in the blog ( https://www.bilibili.com/read/cv2835857 ), and maybe also respond to some comments, if any.

**Comment by mrzjy** [comment]
不客气，乐意至极~

**Comment by peterljq** [comment]
Hi, I have put your tutorial into README. Thank you very much for introducing this project to more developers! 我已经把教程放进README啦，非常感谢对OpenMMD的认可，祝万事胜意！
