### ISSUE TITLE
Check failed: error == cudaSuccess (8 vs. 0)  invalid device function

### ISSUE THREAD

**Issue by Sinsax** [peterljq/OpenMMD#17]
一经搜索好像是显卡或cuda问题？(gtx1660)
看到类似的解决https://github.com/rbgirshick/py-faster-rcnn/issues/2
望解决~

**Comment by peterljq** [comment]
According to a similar issue under Caffe repo, it is mainly the issue of GPU setting. You can find some solutions [here](https://github.com/BVLC/caffe/issues/138).
