### ISSUE TITLE
3d-pose-baseline-vmd  报错

### ISSUE THREAD

**Issue by Asuly** [peterljq/OpenMMD#18]
experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\ls1024\bs64\np\maxnorm\batch_normalization\use_stacked_hourglass\predict_17
子目录或文件 experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\ls1024\bs64\np\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\log 已经存在。
处理: experiments\All\dropout_0.5\epochs_200\lr_0.001\residual\depth_2\ls1024\bs64\np\maxnorm\batch_normalization\use_stacked_hourglass\predict_17\log 时出错。
INFO:__main__:start reading data
Traceback (most recent call last):
  File "src/openpose_3dpose_sandbox_vmd.py", line 484, in <module>
    tf.app.run()
  File "C:\Users\Andy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/openpose_3dpose_sandbox_vmd.py", line 283, in main
    smoothed = read_openpose_json(now_str, idx, subdir)
  File "src/openpose_3dpose_sandbox_vmd.py", line 74, in read_openpose_json
    _tmp_data = data["people"][idx]["pose_keypoints_2d"]
IndexError: list index out of range

**Comment by peterljq** [comment]
Please refer to this issue which has the similar bug with yours: https://github.com/peterljq/OpenMMD/issues/10

**Comment by Asuly** [comment]
> Please refer to this issue which has the similar bug with yours: #10

不一样，我用的是包里的1.3.0.     不过在我把视频里一些不需要的片段剪了后就没有这个错误了
