### ISSUE TITLE
issues of running on mac os

### ISSUE THREAD

**Issue by SoloChen94** [peterljq/OpenMMD#19]
macOS 系统10.14.4 
按照安装说明进行的安装 都没有报错  直到最后开始运行 OpenposeVideo.bat的时候 提示command not found。。。

**Comment by peterljq** [comment]
安装流程参考下这份OpenMMD[中文教程](https://www.bilibili.com/read/cv2835857)吧，应该会解决你的问题。

**Comment by Ai-is-light** [comment]
@SoloChen94 Did you solve your problem?
@peterljq it can only run under the windows?
