### ISSUE TITLE
Use of animation model: Anmicius

### ISSUE THREAD

**Issue by SHMogician** [peterljq/OpenMMD#2]
Hi Peter, may I know where to find the pack of Anmicius body model?

**Comment by SHMogician** [comment]
just write to ask, 有打算把GAN接进来吗？Baseline可能适用2D多一点

**Comment by peterljq** [comment]
有打算在ver 1.2加入，ver 1.1是做user interface，可能期末考之后吧

**Comment by peterljq** [comment]
Hi I have added the GAN feature to the test version. Please proceed to Google Drive to check.

**Comment by SHMogician** [comment]
> Hi I have added the GAN feature to the test version. Please proceed to Google Drive to check.

了解👌，我去下载。
