### ISSUE TITLE
Error on Turing GUP

### ISSUE THREAD

**Issue by 1015145173** [peterljq/OpenMMD#20]
The Code can run on the pascal GPU. But when it's on the Turing the [Open Pose] can't be open
代码跑在帕斯卡架构没问题，可以正常运行。但是运行在图灵上时 [Open Pose]窗口会在打开后无显示，并且在短时间后关闭。无法对视频进行解析。
Cuda version v10.0

**Comment by peterljq** [comment]
这个应该是OpenPose不兼容图灵的问题，可以在OpenPose的issue区问一下。

**Comment by 1015145173** [comment]
嗯，我去问一下
