### ISSUE TITLE
OpenposeTo3D.bat - 'es'不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by MrZhhh** [peterljq/OpenMMD#21]
您好，

我在运行OpenposeTo3D.bat时出现 **'es'不是内部或外部命令**，也不是可运行的程序问题。
并在运行 the detailed information[yes/no/warn]后闪退。运行系统为Windows。
请问 **es (40 sloc) 1.62 KB** 这句话的作用是什么？es是什么东西？

感谢

**Comment by peterljq** [comment]
ES 可能指的是ElasticSearch，请查询下如何在系统中安装对应插件，可参考这篇文章：[链接](https://www.cnblogs.com/ljhdo/p/4887557.html)。
