### ISSUE TITLE
unable to open file:name='data/h36m/camera.h5',no such file or directory

### ISSUE THREAD

**Issue by nostayup** [peterljq/OpenMMD#22]
这个是我库装的不对吗？
该错误出现在第二步，运行OpenposeTo3D.bat时

**Comment by nostayup** [comment]
是我傻逼了吗，这个是需要去openpose下载预训练模型是吧

**Comment by nostayup** [comment]
作者这个工作好棒，期待~

**Comment by peterljq** [comment]
这个报错说明你没有下载在Readme里提供的完整包，请参考下Readme里的installation部分。

**Comment by ecopirate** [comment]
Using the Google Drive, distribution...
Checking the "3D Pose Baseline to VMD" folder and comparing to this:
https://github.com/ArashHosseini/3d-pose-baseline

Looks like the "data" sub-folder was missed in the Google Drive, distribution...

Suggest trying these instructions to recover it:
cd "3D Pose Baseline to VMD" folder 
mkdir data
cd data
wget https://www.dropbox.com/s/e35qv3n6zlkouki/h36m.zip
unzip h36m.zip
rm h36m.zip

**Comment by nostayup** [comment]
> 这个报错说明你没有下载在Readme里提供的完整包，请参考下Readme里的installation部分。
是这样的，我以为直接用GitHub上的就行，非常感谢！
