### ISSUE TITLE
请教一下关于第三步的问题

### ISSUE THREAD

**Issue by nostayup** [peterljq/OpenMMD#24]
作者你好，第一步是通过openpose估计2D的姿态，然后第二步是把2D的姿态估计成3D的姿态，这时已经有3维信息了，那么第三步的估计depth是出于什么考虑？有什么作用呢？

**Comment by nostayup** [comment]
作者你好，第二步产生的那个“smoothed.txt”文件，这个文件里面的都是什么数据，代表什么含义呢？

**Comment by peterljq** [comment]
这个文件主要是记录openpose的关节数据的分析结果，一行对应一帧，详细解释也可以参考repo里附录的原版日文doc

**Comment by nostayup** [comment]
作者你好，感谢你的回答，那第三步生成的depth是什么功能呢？
