### ISSUE TITLE
issue about VMD-3d-pose-baseline-multi

### ISSUE THREAD

**Issue by lin60102** [peterljq/OpenMMD#25]
I have an issue on last step
the error shows that  

INFO:__main__:角度計算開始
INFO:__main__:センター計算開始
Traceback (most recent call last):
  File "applications\pos2vmd_multi.py", line 2305, in <module>
    position_multi_file_to_vmd(position_file, vmd_file, smoothed_file, args.bone, depth_file, args.upright - 1, args.centerxy, args.centerz, args.xangle, args.mdecimation, args.idecimation, args.ddecimation, is_alignment, is_ik, args.heelpos)
  File "applications\pos2vmd_multi.py", line 2189, in position_multi_file_to_vmd
    position_list_to_vmd_multi(positions_multi, vmd_file, smoothed_file, bone_csv_file, depth_file, upright_idx, center_xy_scale, center_z_scale, xangle, mdecimation, idecimation, ddecimation, alignment, is_ik, heelpos)
  File "applications\pos2vmd_multi.py", line 407, in position_list_to_vmd_multi
    calc_center(smoothed_file, bone_csv_file, positions_multi, upright_idx, center_xy_scale, center_z_scale)
  File "applications\pos2vmd_multi.py", line 1760, in calc_center
    upright_ankle_scale = (bone_anke_y / upright_ankle_avg) * (center_xy_scale / 100)
ZeroDivisionError: float division by zero

Also, I found the result of 3d-pose-baseline-vmd is bad.

BTW, Openpose only can use 1.3.0 version.
Any possible to use Openpose1.4 or 1.5?

**Comment by peterljq** [comment]
Sorry for late reply and hope your bugs have been solved :) This application is only a prototype for demostration, so the outcome may not be that satisfying. Do fork your branch and try modifying if you are interested!
