### ISSUE TITLE
How to use 3d pose to generate vmd file

### ISSUE THREAD

**Issue by bailiqun** [peterljq/OpenMMD#4]
Hi, 
Thanks for you impressive work. I just want to know if I get 3d pose from kinect, How could I generate vmd file? 
I can't find index of your code in file **pose2vmd.py**  function **positions_to_frames** ， like pos[14] - pos[11] . how could I know the index of the bone?

**Comment by peterljq** [comment]
Hi! Thanks for your interest in my project. :D
You can find the index of every bone in the file **animasa_miku_born.csv**
linked [https://github.com/peterljq/OpenMMD/blob/master/VMD%203D%20Pose%20Baseline%20Multi-Objects/born/animasa_miku_born.csv](here). Hope the reference helps. Also feel free to fork or download to achieve your own implementation.
