### ISSUE TITLE
Error: Video to write frames could not be opened as...

### ISSUE THREAD

**Issue by kinami30** [peterljq/OpenMMD#47]
So i was trying to use OpenMMD.
I've installed all the necessary libraries.

But everytime i tried to process a video (even the "Real-person.gif" that it comes in the examples), it simply don't work :/

This is the error that it gives me (i'm using **Python 3.7.8** and **Anaconda3**):
![imagen](https://user-images.githubusercontent.com/20263289/88147948-e6406180-cbcb-11ea-861e-b70aa2568412.png)

**Comment by zaanen** [comment]
Hi Kinami30 i think they need to know your executable line.
as i read this error you are missing maybe a \ or casesensitive or the video file is not .avi
or maybe FFmpeg codecs are missing. 

But i could not tell without your command line to execute. So i think the developer can't either.

**Comment by kinami30** [comment]
Well, i just executed the "OpenposeVideo.bat" file u.u
It's weird though because it say in the proyect features that it's compatible with the next video formats:
Input: videos of common formats (AVI, WAV, MOV) or images of common formats (PNG, JPG),

I tried with AVI, MP4 and even with a gif that comes in the proyect) and it didn't work.

And about the FFmpeg codecs, those comes when you install the "opencv-pyhton" (i checked it with the next command in python)
python -c "import cv2; print(cv2.getBuildInformation())"
![imagen](https://user-images.githubusercontent.com/20263289/88245802-792dda00-cc66-11ea-96df-a36bea11ee01.png)

**Comment by zaanen** [comment]
Ok i think i know what you do wrong. 
do you import only the directory or the complete path to the mp4 you want to run?
D:\escritorio\OpenMMD
or
D:\escritorio\OpenMMD\examplemovie.mp4

the second is correct

**Comment by kinami30** [comment]
Thanks!
You response makes me realize of something, and the problem was in the name of the folder where the project was located.
The folder had the name "OpenMMD 1. 0" (it's the name that it's in the rar) and after deleting that "1.0" it seems to work!! :D
