### ISSUE TITLE
 can openmmd vmd files convert to any model Myself created not only Miku Anmicius

### ISSUE THREAD

**Issue by Autumn1992** [peterljq/OpenMMD#7]

**Comment by peterljq** [comment]
Hi thank you for your interest in my project. You can apply the vmd files to ANY of the models that supports MikuMikuDance. Miku (初音未来) and Anmicius (安迷修) are just my personal preference choices.

**Comment by Autumn1992** [comment]
> Hi thank you for your interest in my project. You can apply the vmd files to ANY of the models that supports MikuMikuDance. Miku (初音未来) and Anmicius (安迷修) are just my personal preference choices.

After downloading, firstly activate tensorflow environment in the terminal of anaconda. for this step. i have not found details for seting up. I see 3rdparty/Versions.txt have display some dependencies for windows. did I need set up all of the list. it seems not found tensorflow also.

**Comment by Autumn1992** [comment]
> Hi thank you for your interest in my project. You can apply the vmd files to ANY of the models that supports MikuMikuDance. Miku (初音未来) and Anmicius (安迷修) are just my personal preference choices.

plz ingore my question. I make an idiot mistake

**Comment by Autumn1992** [comment]
> Hi thank you for your interest in my project. You can apply the vmd files to ANY of the models that supports MikuMikuDance. Miku (初音未来) and Anmicius (安迷修) are just my personal preference choices.

OpenposeTo3D.bat can not work correctly.  
Traceback (most recent call last):
  File "src/openpose_3dpose_sandbox_vmd.py", line 9, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
  i have installed tensorflow use pip install. and activate tensorflow. which step i missing?

**Comment by peterljq** [comment]
> > Hi thank you for your interest in my project. You can apply the vmd files to ANY of the models that supports MikuMikuDance. Miku (初音未来) and Anmicius (安迷修) are just my personal preference choices.
> 
> OpenposeTo3D.bat can not work correctly.
> Traceback (most recent call last):
> File "src/openpose_3dpose_sandbox_vmd.py", line 9, in 
> import tensorflow as tf
> ModuleNotFoundError: No module named 'tensorflow'
> i have installed tensorflow use pip install. and activate tensorflow. which step i missing?

I have tested the OpenposeTo3D.bat and it should work properly on Windows. It seems that your console cannot recognise the Tensorflow. I suggest your google the Error: "ModuleNotFoundError: No module named 'tensorflow" or seek answers on stackoverflow. This should be a popular problem under the category of Tensorflow.
