### ISSUE TITLE
about openpose?

### ISSUE THREAD

**Issue by zhra46** [peterljq/OpenMMD#8]
Can openpose produce 3d keypoints from single RGB video?

**Comment by peterljq** [comment]
OpenPose supports single-person 3D key-point detection if your RGB video is of good quality.

**Comment by zhra46** [comment]
Are the output json files contain 3d-keypoints or 2d-kepoints by this line?
`bin\OpenPoseDemo.exe --video %INPUT_VIDEO% --write_json %OUTPUT_JSON_DIR% --write_video %OUTPUT_VIDEO_PATH% --number_people_max %NUMBER_PEOPLE_MAX% 
`

**Comment by peterljq** [comment]
Yes, you can take the json file as the result :)
