### ISSUE TITLE
File too large

### ISSUE THREAD

**Issue by tdotakichan** [peterljq/OpenMMD#9]
Hi is it possible to have the file downloadable with parts? Like a part 1 and part 2 file? The file is just too large to download. If this isn't the right place to ask, can you please redirect me? Because I can't find a comment section here. D:

**Comment by peterljq** [comment]
Hi, I suggest you trying Proxy Down which can efficiently download big files from Google Drive. https://github.com/proxyee-down-org/proxyee-down

**Comment by tdotakichan** [comment]
Oh! Didn't know that existed. Thank you. ^^
